version: "3"

services:
  nginx:
    image: noway56/nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./www:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - backend
  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8080:8080
    stop_grace_period: 1m30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
        placement:
            constraints: [node.role == manager]
    networks:
      - backend

networks:
  backend:
    driver: overlay
