version: "3"

services:
  nginx_deploy:
      # build: .
      # container_name: nginx_deploy
    image: noway56/nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./www:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
